version: '3.1'

services:

  webphpdb:
    build: ./webphpdb
    image: "webphpdb-${VERSIONTAG}"
#    restart: always
    container_name: "webphpdb-${VERSIONTAG}"
    hostname: "webphpdb-${VERSIONTAG}"
    volumes:
      - ${PWD}/mysqldb01:/var/lib/mysql
      - ${PWD}/phpfiles:/var/www/html
    ports:
      - ${EXT_PORT}:80
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLPASSWORD}
#    command: /usr/local/bin/docker-php-entrypoint apache2-foreground && exec /usr/local/bin/docker-entrypoint.sh mysqld 
    command: /wrapper_script.sh
  
      
  balance:
    build: ./balancer
    image: balancer-${VERSIONTAG}
    volumes:
     - ./balancer/balancer.conf:/etc/nginx/conf.d/balancer.conf
     - ./balancer/localhost.key:/etc/nginx/localhost.key
     - ./balancer/localhost.crt:/etc/nginx/localhost.crt
    ports:
     - "80:80"
     - "443:443"
    container_name: "nginx-balancer-${VERSIONTAG}"
    hostname: "nginx-balancer-${VERSIONTAG}"

