---
# tasks file for dockercompose-test

  - name: create test task data directory
    file:
      path: "{{ item }}"
      state: directory
      mode: 0755
    tags: testtask
    with_items:
      - "{{ testtask_root_path }}"
      - "{{ testtask_webphpdb_path }}"
      - "{{ testtask_balancer_path }}"
      - "{{ testtask_mysqldata_path }}"
      - "{{ testtask_wwwfiles_path }}"

  - name: set docker-compose
    template:
      src: docker-compose.yml.j2
      dest: "{{ testtask_root_path}}/docker-compose.yml"
      mode: 0700
    tags: testtask

  - name: docker-compose environment file
    copy:
      src: .env
      dest: "{{ testtask_root_path}}"

  - name: Prepare Dockerfile for webphpdb
    copy:
      src: "Dockerfile.webphpdb"
      dest: "{{ testtask_webphpdb_path }}/Dockerfile"

  - name: Prepare other files for webphpdb
    copy: 
      src: "{{ item }}"
      dest: "{{ testtask_webphpdb_path }}/"
    with_items:
        - wrapper_script.sh
        - config
        - docker-entrypoint.sh

  - name: prepare website file
    copy:
      src: index.php
      dest: "{{ testtask_wwwfiles_path }}/"
      mode: 0777

  - name: set balancer.conf
    template:
      src: balancer.conf.j2
      dest: "{{ testtask_balancer_path }}/balancer.conf"
      mode: 0700

  - name: Prepare Dockfile for balancer
    copy:
      src: Dockerfile.balancer
      dest: "{{ testtask_balancer_path }}/Dockerfile"

  - name: Prepare other files for balancer
    copy:
      src: "{{ item }}"
      dest: "{{ testtask_balancer_path }}/"
      mode: 0700
    with_items:
         - localhost.crt
         - localhost.key

  - name: check if the containers is running
    shell: docker-compose ps
    args:
      chdir: "{{ testtask_root_path }}"
    register: testtaskIsRunning
    changed_when: false

  - name: start testtask
    shell: docker-compose up -d --build --remove-orphans
    args:
      chdir: "{{ testtask_root_path }}"
#    when: (testtaskIsRunning.stdout_lines | length) == 2
